FROM ocaml/opam2:4.10
RUN sudo apt update --fix-missing
RUN sudo apt install -y m4 perl libgmp-dev pkg-config zlib1g-dev python3 \
  python3-pip wget vim tmux --fix-missing

RUN echo "deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/ ./" | sudo tee -a /etc/apt/sources.list
RUN wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | sudo apt-key add
RUN sudo apt install -y libzmq3-dev

RUN sudo apt install -y software-properties-common
RUN sudo add-apt-repository -y ppa:swi-prolog/stable
RUN sudo apt-get --allow-unauthenticated update || true
RUN sudo apt install -y swi-prolog

# OCaml + Jupyter
RUN opam remote add upstream https://github.com/ocaml/opam-repository.git && \
    opam update && opam upgrade
RUN pip3 install jupyter
RUN opam -y depext lwt_ssl
RUN opam install -y lwt_ssl merlin utop user-setup github-unix jupyter

RUN sudo mkdir /usr/local/share/jupyter
RUN sudo chmod a+x /usr/local/share/jupyter
RUN /home/opam/.opam/4.10/bin/ocaml-jupyter-opam-genspec
RUN python3 /home/opam/.local/bin/jupyter kernelspec install --name ocaml-jupyter "$(opam var share)/jupyter" --user

# RISE
RUN pip3 install RISE
COPY .ocamlinit /home/opam/.ocamlinit
ENV PATH $PATH:/home/opam/.local/bin
RUN jupyter-nbextension enable rise --py

# Prolog + Jupyter
RUN sudo --set-home python3 -m pip install --ignore-installed configparser==3.5.0 # XXX KC: Temp Fix
RUN pip3 install git+https://github.com/kayceesrk/jupyter-swi-prolog.git
RUN mkdir ~/.local/share/jupyter/kernels/jswipl
RUN wget https://raw.githubusercontent.com/targodan/jupyter-swi-prolog/master/kernel.json -P ~/.local/share/jupyter/kernels/jswipl

# Egal
RUN pip3 install git+https://github.com/uclnlp/egal.git
RUN jupyter-nbextension install egal --py --user
RUN jupyter-nbextension enable egal --py --user

RUN sudo apt install apt-utils sqlite3

WORKDIR /lectures
